### ISSUE TITLE
Which environnent to test /use

### ISSUE THREAD

**Issue by jejemorg** [soundshed/soundshed-app#1]
Hello,
Nice project, I also have a Spark and I am following your work.
I am used to code but not in TypeScript, but I would like to test your project and so what is your environment to develop your project. 
I'm actually trying to use Visual Studio, but with no luck at this time...

Thanks for your help and thanks for your work !!

**Comment by webprofusion-chrisc** [comment]
Currently this is being developed on windows but mac os and linux would be likely build targets as well, I haven't tried yet.

I've updated the readme with more general info. I use Visual Studio Code (the editor, you don't need full visual studio). The app runs using node and npm (see readme).

Regarding typescript, it's just javascript with types, it's absolutely not a big deal it just helps you build stuff that has added checks to ensure you don't mispell property/method names and it's only lightly used here. For the most part it's exactly the same as modern javascript.
