### ISSUE TITLE
Unresponsive App MacOS Mojave

### ISSUE THREAD

**Issue by EmilioRoberto** [soundshed/soundshed-app#11]
This isn't a big deal, but I have noticed that if I turn off the Bluetooth on my computer, listen to music off my phone, then hibernate my computer and turn off the amp, the next time I turn on the amp to use with Soundshed, the app is unresponsive.  I then force quit and restart it and everything works great.

**Comment by webprofusion-chrisc** [comment]
I noticed this as well, I'm not sure if that sort of thing is going to be easily fixable as it requires a bit more low level tinkering on the bluetooth side - it's most likely the bluetooth comminucation which is hanging.

**Comment by lavabyrd** [comment]
yeah been experiencing it a bit on big sur too. Shame but its not the worst. I hadn't managed to find a way to reliable recreate it though.

**Comment by webprofusion-chrisc** [comment]
@lavabyrd was yours when the computer went to sleep and was resumed? My theory is we need to disconnect bluetooth if the computer is going to sleep and reconnect if it resumes.
