### ISSUE TITLE
Broken User Profile flow

### ISSUE THREAD

**Issue by lavabyrd** [soundshed/soundshed-app#15]
👋🏻 Mentioned this briefly in the discussions but spotted some issues around user login

You can create a new account in the app but not modify it (can deal with that) but if you logout, it logs you out successfully but you can't log back in. Each attempt brings you straight to the "new user signup" modal instead of the "existing user sign in" modal. You could reset the view perhaps on logout or even add a "back" button to let the user go back to login as an existing user. I've not worked on electron before so if you want a PR, I can have a look at it and see what I can do 👍🏻

**Comment by webprofusion-chrisc** [comment]
A PR would be much appreciated, it probably requires a fix to src/components/soundshed/login.tsx - the isRegMode state holds the toggle between the two modes. Not sure what the best approach is. This is also my first Electron app and almost my first react app (I normally do angular or .net).

**Comment by lavabyrd** [comment]
PR coming in tonight so!

**Comment by webprofusion-chrisc** [comment]
Merged now, thanks!
