### ISSUE TITLE
Need to force quit the app after connecting the amp

### ISSUE THREAD

**Issue by tkit0428** [soundshed/soundshed-app#35]
https://user-images.githubusercontent.com/66514683/124905112-49631800-e018-11eb-9152-909c035e5bcc.mp4

**Comment by DieMooPio** [comment]
please fix this

**Comment by webprofusion-chrisc** [comment]
Thanks for the bug report. What version of mac OS are you using and what hardware is it (which mac model/year).

If you try https://app.soundshed.com/ does it work?

**Comment by tkit0428** [comment]
I was using Mac OS Mojave and it's a old 2012 macbook air 😂

**Comment by webprofusion-chrisc** [comment]
It would be interesting to see if this is still a problem with the latest version 1.0.29 which uses a different method to connect to bluetooth and has a newer version of Electron.
