### ISSUE TITLE
New version following Spark update 26/7/21?

### ISSUE THREAD

**Issue by bazmeister** [soundshed/soundshed-app#41]
Hi,
I tried this today, works a treat. Thank you 🙏 

Are there plans to update the app to include the new amps and effects added by Positive Grid yesterday? Hopefully an update is in the pipeline 🤞

**Comment by webprofusion-chrisc** [comment]
Yes, been working on it recently, probably be a few more days as there's another feature I want to squeeze in to this release.

**Comment by bazmeister** [comment]
Excellent news!

I really enjoy using the app on my Mac, at 63 my eyes sometimes struggle with the app on my phone.

Thanks again

Barry

**Comment by webprofusion-chrisc** [comment]
Hi, the new version with updated FX has been released.

**Comment by bazmeister** [comment]
Fabulous!

Thanks for letting me know 😊

Kind regards

Barry
