### ISSUE TITLE
Reverb problem

### ISSUE THREAD

**Issue by atagmester** [soundshed/soundshed-app#47]
Hi
I have some issues with the reverb control. 
When i select a preset, the levels at the reverb tab are OK.  I can control things from the app, but when i use the knob on the device, the app doesn't shows any changes.
If i change the reverb type in the app (where else? :D) everything shows level 0 and i cant control anything (at reverb) from the app anymore. 
The device's knob works (of course) but in the app everything remains at 0.

I tried the windows version and the web app too, with the same results.
Spark has the new (1.4.3.174) firmware...
Sorry for th ebad english, i hope it's understandable.

**Comment by atagmester** [comment]
Ok, now i can't control the reverb from the app. Is it possible if it's a BT connection error made by my notebook?

**Comment by webprofusion-chrisc** [comment]
Hi, the app hasn't changed in a while, I assume you've rebooted your machine and switched the amp off and on?

**Comment by atagmester** [comment]
I've just tried with a second notebook with the same results. With the spark app everything works fine, so i think that my spark isall right.
