### ISSUE TITLE
Can't control  amp - 1.0.29

### ISSUE THREAD

**Issue by aBabyPenguin** [soundshed/soundshed-app#55]
Hi there, I noticed on the new update, that my Windows 10 pc can't control my Spark anymore. When I roll back to 1.0.26, I am able to control it again, no problem. Attached is what my "Amp" page looks like after I connect to my Spark 40. I'm able to change presets, and change tones on the "Tones" page, but I can't control the signal chain.
![soundshed](https://user-images.githubusercontent.com/19317534/192164434-a55f6e75-b8a7-44fb-9117-d9577d14d31f.PNG)

**Comment by webprofusion-chrisc** [comment]
What happens if you click "Refresh"? I've seen this before (amp connects but preset information is not read) and it was some kind of timing issue. Closing and re-opening the app can help as well.
